### ISSUE TITLE
AppImage tar.gz missing

### ISSUE THREAD

**Issue by jan-br** [crabnebula-dev/cargo-packager#134]
Cargo Updater expects a `.AppImage.tar.gz` file with the following content when beeing executed from the context of an Linux AppImage:

```
// ├── [AppName]_[version]_amd64.AppImage.tar.gz    # GZ generated by cargo-packager
// │   └──[AppName]_[version]_amd64.AppImage        # Application AppImage
// └── ...
```

See [here](https://github.com/jan-br/cargo-packager/blob/main/crates/updater/src/lib.rs#L897-L906).
Cargo Packager does not emit these files.

**Comment by denjell-crabnebula** [comment]
I thought that @naman-crabnebula had been working on this

**Comment by jan-br** [comment]
If thats the case, it's not upstream yet

**Comment by denjell-crabnebula** [comment]
I believe it was associated with this work upstream:

https://github.com/tauri-apps/tauri/pull/8618

**Comment by naman-crabnebula** [comment]
Hi There!

Sorry for the confusion, it is just an outdated comment. :sweat_smile: 

Thank you for pointing out. Will remove it soon.
