### ISSUE TITLE
[bug] Node Package Managers ask for `Cargo.toml` file

### ISSUE THREAD

**Issue by naman-crabnebula** [crabnebula-dev/cargo-packager#149]
When we invoke the packager using any of the NPM commands, 

```
# pnpm
pnpm packager --release
# yarn
yarn packager --release
# npm
npx packager --release
```

It produces the error

> ERROR Failed to read cargo metadata: `cargo metadata` exited with an error: error: could not find `Cargo.toml` in `/home/namang/Desktop/Temp/tauri-app` or any parent directory

Even though `Packager.toml` or `package.json` file do have the Cargo Packager configurations.

**How to reproduce :**
1. Create a Tauri app using `pnpm create tauri-app` any of NPM commands.
2. Use `pnpm install` 
3. Add `cargo-packager` using `pnpm add -D @crabnebula/packager`
4. Add Packager configuration in the `Packager.toml` file.
5. Run `pnpm packager --release`

**Expected Behaviour:**
Packager Configuration from `Packager.toml` or `package.json` should be detected and used instead of asking for `Cargo.toml` file again and again.

**Comment by naman-crabnebula** [comment]
I investigated on this issue a bit and found out that 

https://github.com/crabnebula-dev/cargo-packager/blob/main/crates/packager/src/cli/config.rs#L108

Might be causing this issue

**Comment by denjell-crabnebula** [comment]
This is a great finding! Nice job
