### ISSUE TITLE
Lack of helpful error messages

### ISSUE THREAD

**Issue by rafaga** [crabnebula-dev/cargo-packager#159]
I'm trying to build packages on windows and macOS, when I ran the command `cargo packager` on project directory

the following error is shown on terminal

```
ERROR No such file or directory. (os error 2)`
```

When I used the `--verbose` flag, the error message is not better in terms of information

```
DEBUG cargo_packager::shell: Running Command `"rustc" "--print" "cfg"`
DEBUG cargo_packager::shell: debug_assertions
DEBUG cargo_packager::shell: panic="unwind"
DEBUG cargo_packager::shell: target_arch="x86_64"
DEBUG cargo_packager::shell: target_endian="little"
DEBUG cargo_packager::shell: target_env="msvc"
DEBUG cargo_packager::shell: target_family="windows"
DEBUG cargo_packager::shell: target_feature="fxsr"
DEBUG cargo_packager::shell: target_feature="sse"
DEBUG cargo_packager::shell: target_feature="sse2"
DEBUG cargo_packager::shell: target_has_atomic="16"
DEBUG cargo_packager::shell: target_has_atomic="32"
DEBUG cargo_packager::shell: target_has_atomic="64"
DEBUG cargo_packager::shell: target_has_atomic="8"
DEBUG cargo_packager::shell: target_has_atomic="ptr"
DEBUG cargo_packager::shell: target_os="windows"
DEBUG cargo_packager::shell: target_pointer_width="64"
DEBUG cargo_packager::shell: target_vendor="pc"
DEBUG cargo_packager::shell: windows
ERROR cargo_packager::cli: No such file or directory. (os error 2)
```

I'm using `packager.json` with the following content:

```
{
    "name": "telescope",
    "description": "description",
    "longDescription": null,
    "enabled": true,
    "productName": "Telescope",
    "version": "0.0.1",
    "binaries": [
      {
        "path": "telescope",
        "main": true
      }
    ],
    "identifier": "org.rafaga.telescope",
    "beforePackagingCommand": null,
    "beforeEachPackageCommand": null,
    "logLevel": "info",
    "formats": null,
    "targetTriple": null,
    "homepage": "http://github.com/",
    "icons": ["../assets/icon01-256.png","../assets/icon01-1024.png"],
    "authors": [
      "Rafael Amador Galván"
    ],
    "publisher": null,
    "licenseFile": "../LICENSE.md",
    "copyright": null,
    "category": "Utility",
    "fileAssociations": null,
    "resources": [
      {
        "src": "assets/icon01-*.png",
        "target": "assets/icon01.*.png"
      },
      "Lorem ipsum"
    ],
    "externalBinaries": null,
    "windows": {
      "tsp": true,
      "allowDowngrades": true
    },
    "macos": {
      "frameworks": null,
      "entitlements": null
    },
    "deb": null,
    "appimage": null,
    "pacman": null,
    "wix": null,
    "nsis": {
      "compression": "lzma",
      "headerImage": null,
      "installerIcon": null,
      "installMode": "currentUser",
      "languages": [
        "English",
        "Spanish"
      ],
      "displayLanguageSelector": true,
      "appdataPaths": ["$LOCALAPPDATA/$PRODUCTNAME"]
    },
    "dmg":{
      "background": null
    }
  }
```

There is any way to get more helpful error messages?

**Comment by rafaga** [comment]
I tried your suggestion, yet no success. Thank you for taking some time in solving this issue

**Comment by amr-crabnebula** [comment]
could you share the repo with the issue or a simple replica of it so I can take a better look?

**Comment by amr-crabnebula** [comment]
I can see two issues here:
- All paths specified in the config use `../` where it should be just `./` as these files all reside next to the config.
- You're using a `packager.json` config file and when `cargo-packager` sees a dedicated config file, it can't tell it is a rust project or not and so it doesn't set the `outDir` value automatically, so you need to add `"outDir": "target/release"` (the path where cargo outputs your executable) or move your config to `Cargo.toml` under `[package.metadata.packager]` key like this https://github.com/crabnebula-dev/cargo-packager/blob/2ad7706a3c8929dcd50a220c98c2c29032fdf187/examples/egui/Cargo.toml

	I am not sure if we can automatically detect if it is a Rust project with a dedicated config, but as a last resort we can add an option in config to explicitly tells us, maybe `"isRust": true` or something.

**Comment by rafaga** [comment]
Ok, it runs but ... in the config file in the repo I'm Using `Wix Toolkit`, and builds the installer on NSIS , `nsis` configuration part has `null` value.

**Comment by amr-crabnebula** [comment]
wix install is not built by default, set `"formats": ["wix", "nsis", "app", ...etc ]` in the config
