### ISSUE TITLE
[RAD-5] Compliant and secure debian packages 

### ISSUE THREAD

**Issue by amr-crabnebula** [crabnebula-dev/cargo-packager#18]
ref: https://github.com/tauri-apps/tauri/issues/7074

Since our current implementation is ported from tauri-bundler, we are subject to this issue as well.

<sub>[RAD-5](https://linear.app/crabnebula/issue/RAD-5/[packager]-debian-package-compliance)<sub>

**Comment by nazar-pc** [comment]
https://crates.io/crates/cargo-deb generates reasonable packages by default and seems to have library interface that can be used
