### ISSUE TITLE
[resource-resolver] Can not detect the `current_format()` in Arch Linux

### ISSUE THREAD

**Issue by naman-crabnebula** [crabnebula-dev/cargo-packager#188]
The `current_format()` function is not working for AppImage as well as Arch Linux packages.

It is returning `Err(UnkownPackageFormat)`.

## Reproduction

Add `features = ["auto-detect-format"]`, and then try to print the format using

```rust
println!("{:?}", current_format());
```

and then, build it using 

```bash
NO_STRIP=true cargo packager --release --verbose
```

and run the `AppImage` package from the terminal.

**Comment by lucasfernog-crabnebula** [comment]
@naman-crabnebula you must use `before-each-package-command` instead of `before-packaging-command`

**Comment by naman-crabnebula** [comment]
Hi @lucasfernog-crabnebula , thanks a lot for clarifying out.
`AppImage` is now detected correctly. 

However, Arch Linux Package is still not being detected.
