### ISSUE TITLE
(Question) Why there's a CLI on the "crates/packager" and "crates/utils" folders?

### ISSUE THREAD

**Issue by hardBSDk** [crabnebula-dev/cargo-packager#248]

**Comment by FabianLars-crabnebula** [comment]
Well, the `utils` folder is shared across multiple crates: [internally](https://github.com/search?q=repo%3Acrabnebula-dev%2Fcargo-packager+cargo_packager_utils&type=code) and potentially in your project (either directly, or via one of the other crates). With the size of the main packager crate it makes sense to move shared stuff into a seperate project, mainly to (potentially) improve compile times, but also to prevent circular dependencies in the future. Also `packager` is mainly a binary crate, so using it as a library at the same time may be a bit weird (considering its size at least)
