### ISSUE TITLE
[RAD-53] Node.js bindings

### ISSUE THREAD

**Issue by lucasfernog-crabnebula** [crabnebula-dev/cargo-packager#47]
Offering a NPM package for this project would be huge for JavaScript developers that do not want to install Rust and manage dependencies with Cargo. For instance Electron users using `electron-builder` or `electron-packager` could simply install our NPM package and change their build scripts to use it. We could even accept the same configuration objects to simplify the migration process.

This can be achieved with [napi-rs](https://github.com/napi-rs/napi-rs).

<sub>[RAD-54](https://linear.app/crabnebula/issue/RAD-53/[packager]-npm-cli-and-library)<sub>

**Comment by amr-crabnebula** [comment]
[RAD-53](https://linear.app/crabnebula/issue/RAD-53/[packager]-npm-cli-and-library)

**Comment by lucasfernog-crabnebula** [comment]
WIP: https://github.com/crabnebula-dev/cargo-packager/tree/feat/nodejs-binding
