### ISSUE TITLE
Instructions how to re-use packager for existing Electron app

### ISSUE THREAD

**Issue by ega-d** [crabnebula-dev/cargo-packager#80]
Hi everyone, I have an electron app and want to try this packager. Please add some README how can I attach it to the existing project? Now it is based on https://www.npmjs.com/package/@electron-forge/maker-squirrel, and I would like to change it for something better, thanks

**Comment by denjell-crabnebula** [comment]
thanks @ega-d - that's a great idea! we are planning on making a drop-in replacement so you can continue to use the same configuration! would you like to join our discord and help us make this happen? I think we can get this done pretty quickly, especially if you help us vet the approach.

https://discord.gg/HBqPb2yuD2

**Comment by amr-crabnebula** [comment]
Instructions have been added in https://github.com/crabnebula-dev/cargo-packager/tree/main/bindings/packager/nodejs and the package will be released soon.
