### ISSUE TITLE
Wix installs to Program FIles but doesn't give the program elevated privileges

### ISSUE THREAD

**Issue by tigerros** [crabnebula-dev/cargo-packager#89]
When using Wix to create an installer, the installer will put the executable into Program Files, but the executable doesn't have access to Program Files, unless the user always runs the program as an admin. Thus, creating a log file just fails. Also, when uninstalling, the log file is left behind.

How could I specify to install to a location which is not "protected" (preferred), or give the program elevated privileges? Sorry, I'm really new to making installers.

**Comment by amr-crabnebula** [comment]
Unfortunately the `Wix` installer at the moment is limited to `perMachine` installation, which means the default location will be "ProgramFiles". However, we provide an alternative installer `NSIS` which can be either `perMachine` or `perUser` and the `perUser` option will default to `%APPDATA%` directory. 

You can also choose to give your program elevated privileges but that depends on how you build your executable, if using Rust, you can use `embed-manifest` crate https://docs.rs/embed-manifest/latest/embed_manifest/manifest/struct.ManifestBuilder.html#method.requested_execution_level
