### ISSUE TITLE
support adding icons via wildcard/dirs

### ISSUE THREAD

**Issue by wiiznokes** [crabnebula-dev/cargo-packager#96]
It will be cool if we could write this:
```toml
icons = ["ressource/app_icon/*"]
```
because i have currently 9 icons to bundle.

Also, why not renaming `icons` to `app-icon` or `app-icons`?
Personally prefer `app-icon`

**Comment by denjell-crabnebula** [comment]
This exists because of prior work (architectural debt) at tauri-apps.

**Comment by wiiznokes** [comment]
what do you mean by that? it could be retro-compatible, and accept both directory and file

**Comment by denjell-crabnebula** [comment]
If you want to make a PR please reopen the issue, but I see this as really merely cosmetic.

**Comment by wiiznokes** [comment]
I get your point but on Debian, it's advised to provide multiple size of icons, the list can be long actually. 
I made a draft here #99.
